apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zvc5f23aa-go
  janus-idp.io/tekton: zvc5f23aa-go
  backstage.io/kubernetes-id: zvc5f23aa-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvc5f23aa-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
