apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zvc5f23aa-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zvc5f23aa-go 
  name: zvc5f23aa-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zvc5f23aa-go 
